name: nix

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
      - 'lib/resources/CLOJURE_LSP_VERSION'
      - 'lib/resources/CLOJURE_LSP_RELEASED_VERSION'
      - 'docs/**'
      - 'images/**'
      - 'mkdocs.yml'
      - '.github/workflows/bump_deps.yml'
      - '.github/workflows/bump_downstreams.yml'
      - '.github/workflows/ci.yml'
      - '.github/workflows/docs.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/nightly.yml'

jobs:
  nix-flake-test:
    # Confirms that the clojure lsp flake builds fine.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: clojure-lsp
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build
